import { test } from 'vitest';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { prepareProposalEvidence, prepareProposalInterpretation, generateProposalDraftContent } from '../base44/shared/proposalDraftPipeline.js';
import { resolveSections, buildProjectContext } from '../base44/shared/proposalGenerationPrompts.js';
import { buildPreviewAtAGlance, readFrozenPreviewSnapshots } from '../base44/shared/proposalPreviewAuthority.js';
import { buildProposalNarrativeEvidenceGuard } from '../base44/shared/proposalNarrativeEvidenceGuard.js';
import { sanitizeNarrativeHtml, stripNarrativeTables, enforcePredictedLanguage, removeBlanketTonalClaims, enforceSectionScope, enforceApprovedVocabulary, removeStraySectionHeadings, enforceBassConceptSeparation, p17DiffersAcrossVersions } from '../base44/shared/proposalNarrativeSanitizer.js';
import { resolveP17Tradeoff, p17TradeoffSentences } from '../base44/shared/p17TradeoffAuthority.js';
import { resolveSectionTitle } from '../base44/shared/systemDesignSummarySections.js';
import { buildComparisonGlance } from '../src/components/proposal/print/atAGlanceVersions.js';
// All calls below use fixtures; no SDK or database connection.
const snapshot=(id,name,p12,p13,p14,p17)=>({available:true,identity:{projectId:'fixture',versionId:id,engineeringFingerprint:`fp-${id}`},version:{name},
  system:{configuration:{dolby_config:'9.1.6'},channel_layout:{total_discrete:15},product_roles:[{role:'lcr',model_label:id==='low'?'Q6-3':'Q8-5'}]},
  rp22:{parameter_headlines:[{parameter_id:12,achieved_level:p12===106?'L3':'L4',formatted_value:`${p12} dBC`},{parameter_id:13,achieved_level:p13===100?'L2':'L4',formatted_value:`${p13} dBC`},{parameter_id:17,achieved_level:p17}]},
  bass:{available:true,p14:{available:true,achieved_level:p14===115?'L3':'L4',formatted_value:`${p14} dBC`}}});
const entries=[{version_id:'low',version_name:'Level 1 version',snapshot:snapshot('low','Level 1 version',106,100,115,'L3')},{version_id:'high',version_name:'Level 4 version',snapshot:snapshot('high','Level 4 version',116,108,118,'L2')}];
const versions=entries.map((e,i)=>({id:e.version_id,version_name:e.version_name,version_number:i+1}));
const evidence=prepareProposalEvidence(entries,versions,'comparison');
const labels=new Map(versions.map(v=>[v.id,v.version_name]));
const interpretation=prepareProposalInterpretation({suppliedSnapshots:entries,project:{name:'Fixture'},client_brief:'',resolvedType:'comparison',resolvedVersionIds:['low','high'],versionLabelById:labels});
const context=buildProjectContext({name:'Fixture'},'luxury_cinema',null,'',entries[0].snapshot,'comparison',[...labels.values()],null,evidence.comparisonEvidenceText);
const defs=resolveSections('comparison');
const sections=defs.map(s=>({section_type:s.type,section_key:s.key,title:resolveSectionTitle(s.type,s.title,'comparison')}));
const dirty='<p>Intro. Measured variation is proven.</p><table><tbody><tr><td>Bass consistency (P20)</td><td>Measured variation shows a 5 dB reduction.</td></tr></tbody></table>';
const calls=[];
const results=await generateProposalDraftContent({invokeLLM:async args=>{calls.push(args);return args.response_json_schema?{intro_html:dirty}:dirty;},sectionRecords:sections,sectionDefs:defs,resolvedType:'comparison',engineering_snapshot:entries[0].snapshot,comparisonTable:evidence.comparisonTable,versionEvidence:evidence.versionEvidence,projectContext:context,interpretationBlock:interpretation.interpretationBlock});
test('dry-run is admin-only with no writes, live invocation or rollback',()=>{
 const src=fs.readFileSync('base44/functions/previewProposalGeneration/entry.ts','utf8');assert.match(src,/user.role !== 'admin'/);assert.match(src,/dry_run:true,preview_only:true,persisted:false/);
 assert.doesNotMatch(src,/\.(create|bulkCreate|update|bulkUpdate|updateMany|delete|deleteMany|upsert)\s*\(/);assert.doesNotMatch(src,/functions\.invoke|rollbackCreatedProposal|recordIssuedExport/);
});
test('live and preview call the identical extraction, interpretation and prompt pipeline',()=>{
 for(const name of ['generateProposal','previewProposalGeneration']){const src=fs.readFileSync(`base44/functions/${name}/entry.ts`,'utf8');for(const fn of ['prepareProposalEvidence','prepareProposalInterpretation','generateProposalDraftContent','buildProjectContext'])assert.match(src,new RegExp(`${fn}\\(`));}
 const pipeline=fs.readFileSync('base44/shared/proposalDraftPipeline.js','utf8');assert.match(pipeline,/buildSelectedVersionEvidence\(/);assert.match(pipeline,/buildComparisonTable\(/);assert.match(pipeline,/buildSectionPrompt\(/);assert.doesNotMatch(pipeline,/\.entities|functions\.invoke/);
});
test('both version objects preserve fingerprints',()=>{assert.deepEqual(evidence.versionEvidence.map(v=>v.version_id),['low','high']);assert.deepEqual(evidence.versionEvidence.map(v=>v.source_identity.engineeringFingerprint),['fp-low','fp-high']);});
test('At a Glance matches the printed two-version model',()=>{const glance=buildPreviewAtAGlance(evidence.comparisonTable);const printed=buildComparisonGlance({comparisonRows:evidence.comparisonTable.rows,comparisonVersions:evidence.comparisonTable.versions});assert.equal(glance.versionGroups.length,2);assert.deepEqual(glance.versionGroups.map(g=>({name:g.name,cards:g.cards.map(({label,value})=>({label,value}))})),printed.versionGroups);});
test('Key Differences preserves P12/P13/P14, modest P17 copy and trade-off direction',()=>{const row=k=>evidence.comparisonTable.rows.find(r=>r.key===k);assert.deepEqual(row('p12').values,['L3 · 106 dBC','L4 · 116 dBC']);assert.deepEqual(row('p13').values,['L2 · 100 dBC','L4 · 108 dBC']);assert.deepEqual(row('p14').values,['L3 · 115 dBC','L4 · 118 dBC']);assert.deepEqual(row('p17').values,['L3','L2']);assert.equal(row('p17').client_meaning,'Surround and overhead tone stays reasonably consistent, with some variation as effects move around the room.');assert.equal(resolveP17Tradeoff(evidence.comparisonTable).strongerName,'Level 1 version');assert.deepEqual(resolveP17Tradeoff(evidence.comparisonTable).weakerNames,['Level 4 version']);assert.equal(evidence.comparisonTable.rows.some(r=>r.key==='p20'),false);});
test('all six generated sections use the shared sales voice and calculated table',()=>{assert.equal(results.length,6);assert.equal(calls.length,6);assert.ok(results.every(r=>r.html && !r.failed));assert.ok(calls.every(c=>c.prompt.includes('PROPOSAL-ONLY SALES VOICE') && c.prompt.includes('NO POSITIVE CLAIM IS AUTHORISED')));assert.equal(results.find(r=>r.section.section_type==='key_performance_highlights').metadata.comparison_rows,evidence.comparisonTable.rows);});
test('final guard does not infer positive P20 from weak neutral rows',()=>{const guard=buildProposalNarrativeEvidenceGuard(evidence.comparisonTable,evidence.versionEvidence);assert.match(guard,/NO POSITIVE CLAIM IS AUTHORISED/);assert.match(guard,/seat-to-seat consistency should only be claimed where P20 evidence is available/);assert.doesNotMatch(guard,/smaller comparable variation supports a relative improvement/);});
test('generated bodies never carry an AI-written table',()=>{assert.ok(results.every(r=>!/<table|<tr|<td|<th/i.test(r.html)));assert.equal(stripNarrativeTables('<table><tr><td>x</td></tr></table>').trim(),'');});
test('generated bodies never call predicted data measured, proven or confirmed',()=>{assert.ok(results.every(r=>!/\b(measured|proven|confirmed|confirms?)\b/i.test(r.html)));const out=enforcePredictedLanguage('<p>Measured variation is proven and confirmed.</p>');assert.doesNotMatch(out,/\bmeasured\b|\bproven\b|\bconfirmed\b/i);assert.match(out,/Predicted variation/);assert.equal(enforcePredictedLanguage('<p>the predicted result</p>'),'<p>the predicted result</p>');});
test('blanket tonal guarantees are removed where P17 differs',()=>{const body='<p>Every loudspeaker belongs to a matched family, giving matched character throughout the room.</p><p>The Level 1 version keeps the stronger P17 result.</p>';const clean=removeBlanketTonalClaims(body);assert.doesNotMatch(clean,/matched character throughout the room/i);assert.match(clean,/stronger P17 result/);assert.equal(p17DiffersAcrossVersions(evidence.comparisonTable),true);});
test('each theme section keeps to its own parameters',()=>{const scoped=(html,sectionType)=>sanitizeNarrativeHtml(html,{sectionType});assert.doesNotMatch(scoped('<p>P17 timbre is lower in the stronger option.</p><p>P12 rises to 116 dBC at Level 4.</p>','dynamic_range'),/P17/i);assert.match(scoped('<p>P17 timbre is lower in the stronger option.</p><p>P12 rises to 116 dBC at Level 4.</p>','dynamic_range'),/P12 rises/);assert.doesNotMatch(scoped('<p>Screen Dynamic Range reaches L4.</p><p>P17 differs by one level.</p>','timbre_matching'),/P12|Screen Dynamic Range/i);assert.doesNotMatch(scoped('<p>P14 rises to 118 dBC.</p><p>P2 gives 15 discrete channels.</p>','spatial_resolution'),/P14|dBC/i);});
test('a body never duplicates a report section heading, and banned marketing words are rewritten',()=>{assert.doesNotMatch(removeStraySectionHeadings('<h3>System Options Summary</h3><p>P12 rises.</p>'),/System Options Summary/i);assert.match(removeStraySectionHeadings('<h3>Bass Performance</h3><p>Text.</p>'),/Bass Performance/);const out=enforceApprovedVocabulary('<p>The design utilises a reference-style approach and it is important to note that care was taken.</p>');assert.doesNotMatch(out,/utilis|reference-style|important to note/i);assert.match(out,/uses a dedicated approach/);const voice=enforceApprovedVocabulary('<p>A robust and seamless sound field.</p>');assert.doesNotMatch(voice,/robust|seamless/i);assert.match(voice,/solid and smooth sound field/);});
test('guard states the required P17, P20, P2 and vocabulary rules',()=>{const guard=buildProposalNarrativeEvidenceGuard(evidence.comparisonTable,evidence.versionEvidence);assert.match(guard,/stronger P17 surround and overhead timbre result in the frozen evidence/);assert.match(guard,/reviewed for surround and overhead timbre matching before final specification/);assert.match(guard,/seat-to-seat consistency should only be claimed where P20 evidence is available/);assert.match(guard,/the upgrade is not more channels: it is what those channels can deliver/);assert.match(guard,/Never use "measured", "proven" or "confirmed"/);assert.match(guard,/P14 = output capability, impact and authority/);assert.match(guard,/P19 = tonal balance at the reference listening position/);assert.match(guard,/P20 = seat-to-seat consistency/);assert.match(guard,/more screen-stage authority, cleaner dialogue under load/);assert.match(guard,/surround and overhead field keeping up with the screen at higher playback levels/);assert.match(guard,/more bass output authority and more physical impact/);});
const readCalls=[];const frozen=await readFrozenPreviewSnapshots({Proposal:{filter:async(...args)=>{readCalls.push(args);return {items:[{id:'summary',engineering_snapshot:entries[0].snapshot}]};}}},{id:'source',project_id:'fixture',account_id:'account',created_date:'2026-01-01',engineering_snapshot:entries[1].snapshot},['low','high']);
test('historical loader preserves order and reads at cutoff only',()=>{assert.deepEqual(frozen.map(v=>v.version_id),['low','high']);assert.equal(readCalls.length,1);assert.deepEqual(readCalls[0][0].created_date,{$lte:'2026-01-01'});assert.equal(frozen[1].source_record_id,'source');});
test('P17 attribution is never reversed: the guard names the option the frozen evidence shows as stronger',()=>{const guard=buildProposalNarrativeEvidenceGuard(evidence.comparisonTable,evidence.versionEvidence);
 assert.match(guard,/Frozen P17 evidence: Level 1 version: L3 \| Level 4 version: L2\./);
 assert.match(guard,/The Level 1 version currently shows the stronger P17 surround and overhead timbre result in the frozen evidence\./);
 assert.match(guard,/That does not make the Level 4 version poor\./);
 assert.match(guard,/The stronger P17 result belongs to Level 1 version in this evidence, and no other option may be named for it\./);
 assert.doesNotMatch(guard,/Level 4 version currently shows the stronger/i);
 const tradeoff=resolveP17Tradeoff(evidence.comparisonTable);
 assert.equal(tradeoff.strongerName,'Level 1 version');assert.deepEqual(tradeoff.weakerNames,['Level 4 version']);
 assert.match(p17TradeoffSentences(tradeoff).balance,/reviewed for surround and overhead timbre matching before final specification/);});
test('a reversed P17 sentence is replaced with the evidence wording and the balance is kept',()=>{const tradeoff=resolveP17Tradeoff(evidence.comparisonTable);
 const reversed='<p>By contrast, the Level 4 version currently shows a stronger surround and overhead timbre result for the Level 1 version.</p>';
 const clean=sanitizeNarrativeHtml(reversed,{p17Tradeoff:tradeoff,sectionType:'timbre_matching'});
 assert.match(clean,/The Level 1 version currently shows the stronger P17 surround and overhead timbre result in the frozen evidence\./);
 assert.doesNotMatch(clean,/Level 4 version currently shows a stronger|timbre result for the Level 1/i);
 assert.match(clean,/does not make the Level 4 version poor/);
 const correct='<p>The Level 1 version currently shows the stronger P17 surround and overhead timbre result in the frozen evidence.</p><p>It means the stronger system should be reviewed for surround and overhead timbre matching before final specification.</p>';
 const kept=sanitizeNarrativeHtml(correct,{p17Tradeoff:tradeoff,sectionType:'timbre_matching'});
 assert.equal((kept.match(/stronger P17 surround and overhead timbre result in the frozen evidence/g)||[]).length,1);
 assert.match(kept,/It means the stronger system should be reviewed/);});
test('P19 is never described as seat-to-seat consistency and P20 never as the reference-position response',()=>{const guard=buildProposalNarrativeEvidenceGuard(evidence.comparisonTable,evidence.versionEvidence);
 assert.match(guard,/P19 = tonal balance at the reference listening position against target\. That is one position: it is never seat-to-seat variation and never a comparison between seats\./);
 assert.match(guard,/P20 = seat-to-seat consistency\. It is the only parameter that speaks about consistency between seats, and it is never the reference-position response against target\./);
 const conflated=enforceBassConceptSeparation('<p>P19 shows seat-to-seat consistency across all seats.</p><p>P20 is the response against the target at the reference position.</p><p>The Level 1 version keeps a credible 9.1.6 layout.</p>');
 assert.doesNotMatch(conflated,/P19 shows seat-to-seat|P20 is the response against the target/i);
 assert.match(conflated,/credible 9\.1\.6 layout/);
 assert.match(enforceBassConceptSeparation('<p>P19 is not seat-to-seat consistency; that is P20.</p>'),/P19 is not seat-to-seat consistency/);});