// calibrationAuthorityStore.js
// ---------------------------------------------------------------------------
// Reactive store for the Calibration Authority. Per-project, per-version.
// Uses useSyncExternalStore for React integration, same pattern as
// improveBassV2Store.js and designReviewHandoff.js.
//
// The store holds the current Calibration Authority object and provides
// actions to transition its lifecycle:
//   - markCalibrationOptimiserGenerated — optimiser applied calibration
//   - markCalibrationUserModified — user manually edited tuning
//   - markCalibrationStale — geometry changed, calibration no longer valid
//   - resetCalibrationAuthority — clear all calibration state
// ---------------------------------------------------------------------------

import { useSyncExternalStore } from "react";
import { bassCacheKey } from "../bassCacheKey";
import {
  CALIBRATION_STATUS,
  CALIBRATION_SOURCE,
  createCalibrationAuthority,
} from "./calibrationAuthority.js";

const listeners = new Set();
const authorities = new Map();

function getAuthority(projectId, versionId) {
  const key = bassCacheKey(projectId, versionId);
  return authorities.get(key) || null;
}

function subscribe(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

function publish(projectId, versionId, authority) {
  const key = bassCacheKey(projectId, versionId);
  if (authority) {
    authorities.set(key, authority);
  } else {
    authorities.delete(key);
  }
  listeners.forEach((l) => l());
  return authority;
}

/**
 * Set the full calibration authority object.
 */
export function setCalibrationAuthority(projectId, versionId, authority) {
  return publish(projectId, versionId, authority);
}

/**
 * Mark calibration as generated by the optimiser.
 * Called when the V2 optimiser applies calibration tuning.
 *
 * @param {object} params - { basisFingerprint, candidateId, recommendationId, values, stageKey }
 */
export function markCalibrationOptimiserGenerated(projectId, versionId, params) {
  const p = params || {};
  const authority = createCalibrationAuthority({
    basisFingerprint: p.basisFingerprint,
    source: CALIBRATION_SOURCE.OPTIMISER,
    status: CALIBRATION_STATUS.OPTIMISER_GENERATED,
    candidateId: p.candidateId,
    recommendationId: p.recommendationId,
    values: p.values,
    stageKey: p.stageKey,
  });
  return publish(projectId, versionId, authority);
}

/**
 * Mark calibration as current after a successful recalculation.
 * The basis fingerprint is updated to the current geometry.
 */
export function markCalibrationCurrent(projectId, versionId, basisFingerprint, values) {
  const existing = getAuthority(projectId, versionId);
  const authority = createCalibrationAuthority({
    basisFingerprint,
    source: existing?.source || CALIBRATION_SOURCE.OPTIMISER,
    status: CALIBRATION_STATUS.CURRENT,
    candidateId: existing?.candidateId || "",
    recommendationId: existing?.recommendationId || "",
    values: values || existing?.values || [],
    stageKey: existing?.stageKey || "",
  });
  return publish(projectId, versionId, authority);
}

/**
 * Mark calibration as user-modified.
 * Called when the user manually edits delay, gain, polarity, or phase.
 * The basis fingerprint is updated so the calibration is current against
 * the present geometry — the user's edit is intentional.
 */
export function markCalibrationUserModified(projectId, versionId, basisFingerprint, values) {
  const authority = createCalibrationAuthority({
    basisFingerprint,
    source: CALIBRATION_SOURCE.MANUAL,
    status: CALIBRATION_STATUS.USER_MODIFIED,
    values,
  });
  return publish(projectId, versionId, authority);
}

/**
 * Mark calibration as stale.
 * Called when geometry changes and the existing calibration no longer
 * belongs to the current design.
 */
export function markCalibrationStale(projectId, versionId, reason) {
  const existing = getAuthority(projectId, versionId);
  if (!existing) return null;
  const authority = {
    ...existing,
    staleReason: reason || "Geometry changed — calibration needs recalculation",
  };
  return publish(projectId, versionId, authority);
}

/**
 * Reset calibration authority to zero state.
 * Clears all calibration state — the design returns to uncalibrated.
 */
export function resetCalibrationAuthority(projectId, versionId) {
  return publish(projectId, versionId, null);
}

/**
 * React hook: subscribe to the calibration authority for a project/version.
 */
export function useCalibrationAuthority(projectId, versionId) {
  return useSyncExternalStore(
    subscribe,
    () => getAuthority(projectId, versionId),
    () => getAuthority(projectId, versionId),
  );
}

/**
 * Non-hook getter for imperative reads.
 */
export { getAuthority as getCalibrationAuthority };