// AppliedCalibrationAuthorityPanel.jsx
// ---------------------------------------------------------------------------
// UI component that displays the Applied Calibration Authority lifecycle
// state inside the Bass Design Assistant.
//
// Applied Calibration represents the calibration currently assumed by the
// engineering prediction. It is NOT the optimiser recommendation.
//
// Shows:
//   - Status: Current / Needs recalculation / User Accepted
//   - Generated by: Bass Optimiser / Manual Entry
//   - Source: Recommendation ID
//   - Applied: Delay, Gain, Polarity, Phase per subwoofer
//
// When stale, displays:
//   "Current calibration belongs to an earlier version of this design
//    and is no longer authoritative."
//
// Actions:
//   - Recalculate Calibration (triggers the optimiser)
//   - Reset Calibration (clears all calibration to zero)
// ---------------------------------------------------------------------------

import React from "react";
import { RefreshCw, RotateCcw, AlertTriangle, CheckCircle2, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  APPLIED_CALIBRATION_STATUS,
  APPLIED_CALIBRATION_SOURCE,
} from "./appliedCalibrationAuthority.js";

const STATUS_CONFIG = {
  [APPLIED_CALIBRATION_STATUS.CURRENT]: {
    label: "Current",
    color: "#16A34A",
    bg: "#F0FDF4",
    border: "#BBF7D0",
    icon: CheckCircle2,
  },
  [APPLIED_CALIBRATION_STATUS.OPTIMISER_GENERATED]: {
    label: "Current",
    color: "#16A34A",
    bg: "#F0FDF4",
    border: "#BBF7D0",
    icon: CheckCircle2,
  },
  [APPLIED_CALIBRATION_STATUS.STALE]: {
    label: "Needs recalculation",
    color: "#B45309",
    bg: "#FFFBEB",
    border: "#FDE68A",
    icon: AlertTriangle,
  },
  [APPLIED_CALIBRATION_STATUS.USER_ACCEPTED]: {
    label: "User Accepted",
    color: "#1D4ED8",
    bg: "#EFF6FF",
    border: "#BFDBFE",
    icon: CheckCircle2,
  },
  [APPLIED_CALIBRATION_STATUS.USER_MODIFIED]: {
    label: "User Modified",
    color: "#2563EB",
    bg: "#EFF6FF",
    border: "#BFDBFE",
    icon: Wrench,
  },
  [APPLIED_CALIBRATION_STATUS.MANUAL]: {
    label: "Manual",
    color: "#2563EB",
    bg: "#EFF6FF",
    border: "#BFDBFE",
    icon: Wrench,
  },
  [APPLIED_CALIBRATION_STATUS.IMPORTED]: {
    label: "Imported",
    color: "#625143",
    bg: "#F5F5F0",
    border: "#D9D5CE",
    icon: CheckCircle2,
  },
  [APPLIED_CALIBRATION_STATUS.UNKNOWN]: {
    label: "No calibration",
    color: "#625143",
    bg: "#F5F5F0",
    border: "#D9D5CE",
    icon: AlertTriangle,
  },
};

function formatPolarity(p) {
  const n = Number(p) || 1;
  return n < 0 ? "Inverted" : "Normal";
}

function formatPhase(deg) {
  const d = Number(deg) || 0;
  return `${d.toFixed(0)}°`;
}

function formatDelay(ms) {
  const v = Number(ms) || 0;
  return `${v.toFixed(1)} ms`;
}

function formatGain(db) {
  const v = Number(db) || 0;
  const sign = v > 0 ? "+" : "";
  return `${sign}${v.toFixed(1)} dB`;
}

export default function AppliedCalibrationAuthorityPanel({
  authority,
  isStale,
  staleReason,
  onRecalculate,
  onReset,
  busy,
}) {
  if (!authority) return null;

  const rawStatus = isStale ? APPLIED_CALIBRATION_STATUS.STALE : (authority.status || APPLIED_CALIBRATION_STATUS.UNKNOWN);
  const config = STATUS_CONFIG[rawStatus] || STATUS_CONFIG[APPLIED_CALIBRATION_STATUS.UNKNOWN];
  const StatusIcon = config.icon;
  const values = Array.isArray(authority.values) ? authority.values : [];
  const hasValues = values.length > 0;

  return (
    <div
      className="mt-3 rounded-lg border p-4"
      style={{ borderColor: config.border, background: config.bg }}
      data-calibration-authority-panel="true"
    >
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <StatusIcon className="h-4 w-4" style={{ color: config.color }} />
          <span className="text-[13px] font-semibold text-[#1B1A1A]">
            Current Calibration
          </span>
        </div>
        <span
          className="text-[11px] font-semibold px-2 py-0.5 rounded-full"
          style={{ color: config.color, background: config.bg, border: `1px solid ${config.border}` }}
        >
          {config.label}
        </span>
      </div>

      {/* Stale warning */}
      {isStale && (
        <div className="mt-2 rounded-md border border-amber-300 bg-amber-50 p-2.5">
          <div className="flex items-start gap-1.5">
            <AlertTriangle className="h-3.5 w-3.5 text-amber-700 flex-shrink-0 mt-0.5" />
            <p className="text-[11px] leading-relaxed text-amber-800">
              {staleReason || "Current calibration belongs to an earlier version of this design and is no longer authoritative."}
            </p>
          </div>
        </div>
      )}

      {/* Metadata */}
      <div className="mt-3 space-y-1.5">
        <div className="flex items-center gap-2 text-[11px]">
          <span className="text-[#625143] font-medium min-w-[90px]">Generated by:</span>
          <span className="text-[#1B1A1A]">{authority.source || APPLIED_CALIBRATION_SOURCE.UNKNOWN}</span>
        </div>
        {authority.candidateId && (
          <div className="flex items-center gap-2 text-[11px]">
            <span className="text-[#625143] font-medium min-w-[90px]">Source:</span>
            <span className="text-[#1B1A1A] font-mono text-[10px]">
              Recommendation {authority.candidateId.slice(0, 12)}
            </span>
          </div>
        )}
        {authority.stageKey && (
          <div className="flex items-center gap-2 text-[11px]">
            <span className="text-[#625143] font-medium min-w-[90px]">Stage:</span>
            <span className="text-[#1B1A1A] capitalize">{authority.stageKey}</span>
          </div>
        )}
      </div>

      {/* Applied values */}
      {hasValues && (
        <div className="mt-3 rounded-md border border-[#D9D5CE] bg-white p-3">
          <div className="text-[10px] font-semibold text-[#625143] uppercase tracking-wide mb-2">
            Applied Calibration
          </div>
          <div className="space-y-1.5">
            {values.map((v, i) => (
              <div key={v.id || i} className="flex items-center gap-3 text-[11px]">
                <span className="text-[#625143] font-medium min-w-[50px]">Sub {i + 1}</span>
                <span className="text-[#1B1A1A] font-mono">
                  {formatDelay(v.delayMs)}
                </span>
                <span className="text-[#1B1A1A] font-mono">
                  {formatGain(v.gainDb)}
                </span>
                <span className="text-[#1B1A1A] font-mono">
                  {formatPolarity(v.polarity)}
                </span>
                <span className="text-[#1B1A1A] font-mono">
                  {formatPhase(v.phaseControlDeg)}
                </span>
              </div>
            ))}
          </div>
          <div className="mt-2 flex items-center gap-4 text-[9px] text-[#9A9A9A] uppercase tracking-wide">
            <span className="min-w-[50px]">&nbsp;</span>
            <span>Delay</span>
            <span>Level</span>
            <span>Polarity</span>
            <span>Phase</span>
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="mt-3 flex items-center gap-2">
        {isStale && (
          <Button
            type="button"
            size="sm"
            className="h-8 bg-[#213428] text-white hover:bg-[#3E4349]"
            onClick={onRecalculate}
            disabled={busy}
          >
            <RefreshCw className="h-3.5 w-3.5 mr-1.5" />
            Recalculate Calibration
          </Button>
        )}
        <Button
          type="button"
          size="sm"
          variant="outline"
          className="h-8 border-[#D9D5CE] text-[#625143] hover:bg-[#F5F5F0]"
          onClick={onReset}
          disabled={busy}
        >
          <RotateCcw className="h-3.5 w-3.5 mr-1.5" />
          Reset Calibration
        </Button>
      </div>
    </div>
  );
}