// appliedCalibrationAuthorityStore.js
// ---------------------------------------------------------------------------
// Reactive store for the Applied Calibration Authority. Per-project,
// per-version. Uses useSyncExternalStore for React integration, same pattern
// as improveBassV2Store.js and designReviewHandoff.js.
//
// The store holds the current Applied Calibration Authority object and
// provides actions to transition its lifecycle:
//   - markAppliedCalibrationOptimiserGenerated — optimiser applied calibration
//   - markAppliedCalibrationUserModified — user manually edited tuning
//   - markAppliedCalibrationStale — geometry changed, calibration no longer valid
//   - resetAppliedCalibrationAuthority — clear all calibration state
//
// Applied Calibration represents the calibration currently assumed by the
// engineering prediction. It is NOT the optimiser recommendation.
// ---------------------------------------------------------------------------

import { useSyncExternalStore } from "react";
import { bassCacheKey } from "../bassCacheKey";
import {
  APPLIED_CALIBRATION_STATUS,
  APPLIED_CALIBRATION_SOURCE,
  createAppliedCalibrationAuthority,
} from "./appliedCalibrationAuthority.js";

const listeners = new Set();
const authorities = new Map();

function getAuthority(projectId, versionId) {
  const key = bassCacheKey(projectId, versionId);
  return authorities.get(key) || null;
}

function subscribe(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

function publish(projectId, versionId, authority) {
  const key = bassCacheKey(projectId, versionId);
  if (authority) {
    authorities.set(key, authority);
  } else {
    authorities.delete(key);
  }
  listeners.forEach((l) => l());
  return authority;
}

/**
 * Set the full applied calibration authority object.
 */
export function setAppliedCalibrationAuthority(projectId, versionId, authority) {
  return publish(projectId, versionId, authority);
}

/**
 * Mark applied calibration as generated by the optimiser.
 * Called when the V2 optimiser applies calibration tuning.
 *
 * @param {object} params - { basisFingerprint, candidateId, recommendationId, values, stageKey }
 */
export function markAppliedCalibrationOptimiserGenerated(projectId, versionId, params) {
  const p = params || {};
  const authority = createAppliedCalibrationAuthority({
    basisFingerprint: p.basisFingerprint,
    source: APPLIED_CALIBRATION_SOURCE.OPTIMISER,
    status: APPLIED_CALIBRATION_STATUS.OPTIMISER_GENERATED,
    candidateId: p.candidateId,
    recommendationId: p.recommendationId,
    values: p.values,
    stageKey: p.stageKey,
  });
  return publish(projectId, versionId, authority);
}

/**
 * Mark applied calibration as current after a successful recalculation.
 * The basis fingerprint is updated to the current geometry.
 */
export function markAppliedCalibrationCurrent(projectId, versionId, basisFingerprint, values) {
  const existing = getAuthority(projectId, versionId);
  const authority = createAppliedCalibrationAuthority({
    basisFingerprint,
    source: existing?.source || APPLIED_CALIBRATION_SOURCE.OPTIMISER,
    status: APPLIED_CALIBRATION_STATUS.CURRENT,
    candidateId: existing?.candidateId || "",
    recommendationId: existing?.recommendationId || "",
    values: values || existing?.values || [],
    stageKey: existing?.stageKey || "",
  });
  return publish(projectId, versionId, authority);
}

/**
 * Mark applied calibration as user-modified.
 * Called when the user manually edits delay, gain, polarity, or phase.
 * The basis fingerprint is updated so the calibration is current against
 * the present geometry — the user's edit is intentional.
 */
export function markAppliedCalibrationUserModified(projectId, versionId, basisFingerprint, values) {
  const authority = createAppliedCalibrationAuthority({
    basisFingerprint,
    source: APPLIED_CALIBRATION_SOURCE.MANUAL,
    status: APPLIED_CALIBRATION_STATUS.USER_MODIFIED,
    values,
  });
  return publish(projectId, versionId, authority);
}

/**
 * Mark applied calibration as stale.
 * Called when geometry changes and the existing calibration no longer
 * belongs to the current design.
 */
export function markAppliedCalibrationStale(projectId, versionId, reason) {
  const existing = getAuthority(projectId, versionId);
  if (!existing) return null;
  const authority = {
    ...existing,
    staleReason: reason || "Geometry changed — calibration needs recalculation",
  };
  return publish(projectId, versionId, authority);
}

/**
 * Reset applied calibration authority to zero state.
 * Clears all calibration state — the design returns to uncalibrated.
 */
export function resetAppliedCalibrationAuthority(projectId, versionId) {
  return publish(projectId, versionId, null);
}

/**
 * React hook: subscribe to the applied calibration authority for a project/version.
 */
export function useAppliedCalibrationAuthority(projectId, versionId) {
  return useSyncExternalStore(
    subscribe,
    () => getAuthority(projectId, versionId),
    () => getAuthority(projectId, versionId),
  );
}

/**
 * Non-hook getter for imperative reads.
 */
export { getAuthority as getAppliedCalibrationAuthority };