// THE single source of truth mapping Role -> Module -> Access Level.
// To change what a role can do, edit this file only — nothing else in the app
// should hardcode role/module access.

import { ROLES } from "./roles";
import { MODULES } from "./modules";
import { LEVELS } from "./permissionLevels";

const { NONE, READ, EDIT, ADMIN } = LEVELS;

export const PERMISSION_MANIFEST = {
  [ROLES.SUPER_ADMIN]: {
    [MODULES.PROJECTS]: ADMIN,
    [MODULES.ROOM_DESIGNER]: ADMIN,
    [MODULES.BASS_SIMULATION]: ADMIN,
    [MODULES.SPL_CALCULATOR]: ADMIN,
    [MODULES.RP22_REPORTS]: ADMIN,
    [MODULES.RP23_REPORTS]: ADMIN,
    [MODULES.MEASURED_DATASETS]: ADMIN,
    [MODULES.PRODUCTS]: ADMIN,
    [MODULES.ADMIN_DASHBOARD]: ADMIN,
    [MODULES.SYSTEM_HEALTH]: ADMIN,
    [MODULES.USER_MANAGEMENT]: ADMIN,
    [MODULES.COMPANY_MANAGEMENT]: ADMIN,
    [MODULES.AUDIT_LOG]: ADMIN,
    [MODULES.PRICING]: ADMIN,
  },

  [ROLES.ADMINISTRATOR]: {
    [MODULES.PROJECTS]: ADMIN,
    [MODULES.ROOM_DESIGNER]: ADMIN,
    [MODULES.BASS_SIMULATION]: ADMIN,
    [MODULES.SPL_CALCULATOR]: ADMIN,
    [MODULES.RP22_REPORTS]: ADMIN,
    [MODULES.RP23_REPORTS]: ADMIN,
    [MODULES.MEASURED_DATASETS]: READ,
    [MODULES.PRODUCTS]: ADMIN,
    [MODULES.ADMIN_DASHBOARD]: ADMIN,
    [MODULES.SYSTEM_HEALTH]: ADMIN,
    [MODULES.USER_MANAGEMENT]: ADMIN,
    [MODULES.COMPANY_MANAGEMENT]: ADMIN,
    [MODULES.AUDIT_LOG]: ADMIN,
    [MODULES.PRICING]: ADMIN,
  },

  [ROLES.DESIGNER_PRO]: {
    [MODULES.PROJECTS]: EDIT,
    [MODULES.ROOM_DESIGNER]: EDIT,
    [MODULES.BASS_SIMULATION]: EDIT,
    [MODULES.SPL_CALCULATOR]: EDIT,
    [MODULES.RP22_REPORTS]: EDIT,
    [MODULES.RP23_REPORTS]: EDIT,
    [MODULES.MEASURED_DATASETS]: READ,
    [MODULES.PRODUCTS]: READ,
    [MODULES.ADMIN_DASHBOARD]: NONE,
    [MODULES.SYSTEM_HEALTH]: NONE,
    [MODULES.USER_MANAGEMENT]: NONE,
    [MODULES.COMPANY_MANAGEMENT]: NONE,
    [MODULES.AUDIT_LOG]: NONE,
    [MODULES.PRICING]: NONE,
  },

  [ROLES.DESIGNER_LITE]: {
    [MODULES.PROJECTS]: EDIT,
    [MODULES.ROOM_DESIGNER]: EDIT,
    [MODULES.BASS_SIMULATION]: EDIT,
    [MODULES.SPL_CALCULATOR]: EDIT,
    [MODULES.RP22_REPORTS]: EDIT,
    [MODULES.RP23_REPORTS]: READ,
    [MODULES.MEASURED_DATASETS]: READ,
    [MODULES.PRODUCTS]: READ,
    [MODULES.ADMIN_DASHBOARD]: NONE,
    [MODULES.SYSTEM_HEALTH]: NONE,
    [MODULES.USER_MANAGEMENT]: NONE,
    [MODULES.COMPANY_MANAGEMENT]: NONE,
    [MODULES.AUDIT_LOG]: NONE,
    [MODULES.PRICING]: NONE,
  },

  [ROLES.VIEWER]: {
    [MODULES.PROJECTS]: READ,
    [MODULES.ROOM_DESIGNER]: READ,
    [MODULES.BASS_SIMULATION]: READ,
    [MODULES.SPL_CALCULATOR]: READ,
    [MODULES.RP22_REPORTS]: READ,
    [MODULES.RP23_REPORTS]: READ,
    [MODULES.MEASURED_DATASETS]: NONE,
    [MODULES.PRODUCTS]: READ,
    [MODULES.ADMIN_DASHBOARD]: NONE,
    [MODULES.SYSTEM_HEALTH]: NONE,
    [MODULES.USER_MANAGEMENT]: NONE,
    [MODULES.COMPANY_MANAGEMENT]: NONE,
    [MODULES.AUDIT_LOG]: NONE,
    [MODULES.PRICING]: NONE,
  },
};