export const BEST_SUB_LAYOUT_CONSTANTS = Object.freeze({
  candidateDefinitionVersion: "rp22-guided-layouts-v2-hierarchy",
  previewPointsPerOctave: 8,
  debounceMs: 80,
  maximumRecommendations: 3,
  allowedSourceCounts: [1, 2, 4],
  fallbackSourceHeightM: 0.05,
  minimumWallClearanceM: 0.1,
  openingClearanceM: 0.2,
  nullRule: { smoothingRadiusBins: 1, shoulderRadiusBins: 4, minimumContiguousBins: 2, destructiveDepthDb: 8 },
  extension: { referenceStartHz: 60, referenceEndHz: 100, allowedDropDb: 10 },
  efficiency: {
    assessmentStartHz: 30,
    assessmentEndHz: 120,
    strongMinRelativeDb: -3,
    balancedMinRelativeDb: -6,
    transferBaselinePercentile: 0.75,
    explanation: "Room-minus-direct transfer over 30–120 Hz, referenced to that seat's upper-quartile transfer and averaged using cancellation-only residuals. Identical source coordinates, count and listeners remove source level and coherent source-count gain; the upper-quartile baseline removes common room gain without allowing peaks to compensate for losses.",
  },
  grades: {
    aPlusMaxVariationDb: 4,
    aMaxVariationDb: 6,
    bMaxVariationDb: 9,
    individualSeatMaxNullDb: 8,
    individualSeatMaxExtensionHz: 40,
  },
  tieTolerance: { nullDepthDb: 0.1, variationDb: 0.1, extensionHz: 0.5, efficiencyDb: 0.1 },
});