export const BEST_SUB_LAYOUT_CONSTANTS = Object.freeze({
  candidateDefinitionVersion: "phase3-layouts-v1",
  previewPointsPerOctave: 8,
  debounceMs: 80,
  maximumRecommendations: 3,
  allowedSourceCounts: [1, 2, 4],
  sourceHeightM: 0.3,
  nullRule: {
    smoothingRadiusBins: 1,
    shoulderRadiusBins: 4,
    minimumContiguousBins: 2,
    destructiveDepthDb: 8,
  },
  extension: { referenceStartHz: 60, referenceEndHz: 100, allowedDropDb: 10 },
  efficiency: { strongMinDb: 92, balancedMinDb: 86 },
  grades: {
    aPlusMaxVariationDb: 4,
    aMaxVariationDb: 6,
    bMaxVariationDb: 9,
    individualSeatMaxNullDb: 8,
    individualSeatMaxExtensionHz: 40,
  },
  tieTolerance: { nullDepthDb: 0.1, variationDb: 0.1, extensionHz: 0.5, efficiencyDb: 0.1 },
});

export const BEST_SUB_LAYOUT_PHYSICS_PARAMS = Object.freeze({
  surfaceAbsorption: Object.freeze({ front: 0.3, back: 0.3, left: 0.3, right: 0.3, ceiling: 0.3, floor: 0.3 }),
  qStrategy: "ab_corrected",
  enableRewCoreReflections: false,
  roomDamping: 20,
  axialQ: 4,
  modalSourceReferenceMode: "existing",
  modalGainScalar: 1,
  modalDistanceBlend: 0,
  modalStorageMode: "constant",
  propagationPhaseScale: 0,
  disableReflectionPhaseJitter: false,
  disableReflectionCoherenceWeight: false,
  mute68HzAxialMode: false,
  debugDisableModalContribution: false,
  rewParityFieldMode: "full_field",
  debugMode200Multiplier: 1,
  reflectionGainScale: 1,
  modalCoherenceMode: "standard",
  highOrderAxialScale: 1,
  rewModalBandwidthScale: 1,
});