/**
 * adiAssessmentBuilder.js
 * -----------------------
 * The single authoritative ADI Assessment builder.
 *
 * ARCHITECTURE:
 *
 *   Optimiser
 *       ↓
 *   Published Engineering Authority          ← immutable, singular
 *       ├── RP22
 *       ├── Design Rating
 *       ├── Engineering Summary
 *       ├── ADI Assessment                  ← this builder
 *       ├── Technical Report
 *       ├── Dealer Presentation
 *       ├── Client Proposal
 *       └── Interactive Presentation
 *
 * The designReviewHandoff object IS the Published Engineering Authority.
 * There is only ever one object with that role. It is not a "snapshot" —
 * it is the permanent engineering truth for a design version, published
 * once and never modified. Every consumer reads from this one authority.
 *
 * ADI consumes the Published Engineering Authority directly — it is NOT a
 * child of the Engineering Summary. Both are independent consumers of the
 * same engineering truth.
 *
 * ADI is professional engineering commentary — never a score, never another
 * RP22 parameter, never a list of faults. It complements the Design Rating.
 * It never replaces it, and it never repeats it. ADI references the Design
 * Rating outcome; it does not restate the levels.
 *
 * One builder. Many consumers. Every surface — Technical Report, Dealer
 * Presentation, Client Proposal, PDF, Interactive Presentation — calls
 * buildAdiAssessment() and gets the same assessment. The next surface is
 * not another report — it is another view of the same engineering.
 *
 * AUDIENCE DEPTH — not audience wording:
 *   The builder accepts an optional `audience` parameter. This does NOT
 *   change the wording of the engineering truth. It changes the DEPTH of
 *   explanation. The engineering truth is identical for every audience.
 *
 *     technical — Everything. Engineering. Trade-offs. Limitations.
 *     dealer    — Engineering conclusions. Commercial language.
 *                 Recommendations. No implementation detail.
 *     client    — Benefits. Experience. Confidence.
 *                 No engineering terminology.
 *
 *   Exactly the same engineering truth. Just progressively simplified.
 *
 * ARCHITECTURAL INVARIANTS — these protect the architecture forever:
 *
 *   • ADI is the authoritative narrative layer.
 *   • The Published Engineering Authority is immutable.
 *   • Audience selection changes presentation only.
 *   • Engineering truth never changes.
 *
 * Pure: no React, no UI, no side effects. Reads only from the Published
 * Engineering Authority.
 */

import { getRoomDesignRatingDesignation } from "./designRatingPresentation";

const LEVEL_RANK = { L1: 1, L2: 2, L3: 3, L4: 4 };

/**
 * The footer line shown beneath every ADI Assessment, on every consumer
 * surface. Reinforces the brand without mentioning AI or language models.
 */
export const ADI_FOOTER =
  "Engineering Assessment generated by Artcoustic Design Intelligence. Reviewed against the published engineering result.";

/**
 * Extract the engineering summary from the Published Engineering Authority.
 *
 * The Published Engineering Authority is the full designReviewHandoff
 * object. The engineering summary is one structured field within it. ADI
 * reads it directly from the authority — it does not receive it as a
 * separate input.
 */
function resolveEngineeringSummary(publishedAuthority) {
  if (!publishedAuthority) return null;
  return publishedAuthority.engineeringSummary
    ?? publishedAuthority.rating?.engineeringSummary
    ?? null;
}

/**
 * Extract the lowest achieved floor level across the three RP22 performance
 * categories (Spatial Resolution, Dynamic Range, Timbre Matching) for a
 * seating group. Screen / Viewing Geometry is separately governed and
 * excluded. FAIL is excluded — a FAIL triggers a different narrative path.
 *
 * @param {Array} categories — engineeringSummary.{primary|secondary}.categories
 * @returns {string|null} — "L1".."L4" or null
 */
function getSeatingGroupFloor(categories) {
  if (!Array.isArray(categories)) return null;
  const rp22Categories = categories.filter(
    (cat) => cat?.hasContribs && !cat?.isScreen && !cat?.hasFail,
  );
  const levels = rp22Categories
    .map((cat) => cat?.floorLevel)
    .filter((level) => level && LEVEL_RANK[level]);
  if (!levels.length) return null;
  return levels.sort((a, b) => LEVEL_RANK[a] - LEVEL_RANK[b])[0];
}

/**
 * Check if any category in the seating group has a genuine FAIL.
 */
function hasAnyFail(categories) {
  if (!Array.isArray(categories)) return false;
  return categories.some((cat) => cat?.hasFail);
}

/**
 * Resolve the P19/P20 bass parameter level for a seating scope.
 * Keys may be lowercase "p19"/"p20" in parameterSummaries.
 */
function getBassLevel(parameterSummaries, scope, paramKey) {
  const scopeSummary = parameterSummaries?.[scope];
  if (!scopeSummary) return null;
  const param = scopeSummary?.[paramKey] || scopeSummary?.[paramKey.toUpperCase()];
  const level = param?.level;
  return level && LEVEL_RANK[level] ? level : null;
}

// ── Overall Assessment sentence builders ─────────────────────────────────
// Every assessment follows the same four-sentence structure:
//   1. Design strength
//   2. Primary achievement
//   3. Remaining limitation
//   4. Overall confidence
// The wording changes. The structure does not.

function buildStrengthSentence({ bassStrong, bassModerate, coverage }) {
  if (bassStrong) {
    return "The selected loudspeaker system provides a balanced and consistent listening experience throughout the primary seating area.";
  }
  if (bassModerate) {
    return "The selected loudspeaker system provides a well-balanced listening experience across the primary seating area.";
  }
  return "The selected loudspeaker system provides a balanced listening experience across the seating area.";
}

function buildAchievementSentence({ meetsObjective, primaryHasFail }) {
  if (primaryHasFail) {
    return "The design meets the foundational RP22 objectives with specific parameters requiring attention.";
  }
  if (meetsObjective) {
    return "The design comfortably achieves the selected RP22 objectives while maintaining good bass uniformity across the room.";
  }
  return "The design meets the selected design objectives with consistent performance across the listening area.";
}

function buildLimitationSentence({ primaryHasFail, hasImprovements, compromisedSeatCount }) {
  if (primaryHasFail) {
    return "The remaining limitations are primarily physical and would require changes to room geometry or system specification rather than further calibration.";
  }
  if (hasImprovements && compromisedSeatCount > 0) {
    return "The remaining improvements are refinements relating to seating position rather than fundamental limitations of the loudspeaker system or calibration.";
  }
  if (hasImprovements) {
    return "The remaining improvements are refinements rather than fundamental limitations.";
  }
  return "No significant limitations remain in the current configuration.";
}

function buildConfidenceSentence({ meetsObjective, primaryHasFail }) {
  if (primaryHasFail) {
    return "This design would benefit from addressing the identified limitations before final recommendation.";
  }
  if (meetsObjective) {
    return "This is a well-balanced design that can be recommended with confidence.";
  }
  return "This design provides a solid foundation with opportunities for further refinement.";
}

/**
 * Build the ADI Assessment from the Published Engineering Authority.
 *
 * @param {Object} publishedAuthority — the Published Engineering Authority
 *   (the designReviewHandoff object published by the Room Designer). There
 *   is only ever one object with this role. ADI reads the engineering
 *   summary field directly from it.
 * @param {Object} [options]
 * @param {string} [options.audience="technical"] — audience depth selector.
 *   "technical" | "dealer" | "client". This changes the DEPTH of
 *   explanation, not the engineering truth. The same conclusions, the same
 *   outcomes, the same design rating — progressively simplified.
 *   Currently only "technical" is implemented; the structure is in place
 *   so dealer/client depths can be added without rewriting the engineering
 *   content.
 * @returns {{ highlights: string[], improvements: Array<{action, why, benefit}>, overallAssessment: string, designation: string|null, footer: string } | null}
 */
export function buildAdiAssessment(publishedAuthority, { audience = "technical" } = {}) {
  if (!publishedAuthority) return null;

  const engineeringSummary = resolveEngineeringSummary(publishedAuthority);
  if (!engineeringSummary) return null;

  const primaryCats = engineeringSummary.primary?.categories || [];
  const secondaryCats = engineeringSummary.secondary?.categories || [];
  const primaryHasFail = hasAnyFail(primaryCats);
  const secondaryHasFail = hasAnyFail(secondaryCats);

  const projectRating = engineeringSummary.project?.rating;
  const designation = getRoomDesignRatingDesignation(projectRating);
  const dpi = engineeringSummary.project?.designPerformanceIndex;

  const compromisedSeatCount =
    engineeringSummary.project?.reportCounts?.compromisedSeatCount || 0;
  const coverage = engineeringSummary.project?.coverage;

  // P19 (response fit) and P20 (seat consistency) for bass commentary.
  // ADI references the bass outcome qualitatively — it never states the level.
  const p19Primary = getBassLevel(engineeringSummary.parameterSummaries, "primary", "p19");
  const p20Primary = getBassLevel(engineeringSummary.parameterSummaries, "primary", "p20");

  const bassStrong =
    p19Primary && p20Primary &&
    LEVEL_RANK[p19Primary] >= 3 && LEVEL_RANK[p20Primary] >= 3;
  const bassModerate =
    p19Primary && p20Primary &&
    (LEVEL_RANK[p19Primary] >= 2 || LEVEL_RANK[p20Primary] >= 2);

  // Design meets objective: no FAIL, DPI >= 60 (High Performance or above).
  const meetsObjective = !primaryHasFail && dpi != null && dpi >= 60;

  // ── Highlights — always begin positively ──────────────────────────────
  // ADI references the Design Rating outcome; it never restates the levels.
  const highlights = [];

  if (bassStrong) {
    highlights.push("The primary listening area delivers a consistent and balanced bass response that meets the selected design objectives.");
  } else if (bassModerate) {
    highlights.push("The primary listening area delivers a well-controlled bass response across the selected listening positions.");
  }
  if (!primaryHasFail && !secondaryHasFail) {
    highlights.push("The listening experience remains well balanced across the seating area.");
  }
  if (meetsObjective) {
    highlights.push("The selected loudspeaker system comfortably achieves the chosen design objective.");
  }
  if (coverage?.statement) {
    highlights.push("The design provides balanced coverage throughout the seating area.");
  }

  // Always have at least one positive highlight.
  if (highlights.length === 0) {
    highlights.push("The design has been evaluated against CEDIA RP22 performance criteria.");
  }

  // ── Improvements to Consider — only meaningful engineering benefit ─────
  const improvements = [];

  if (compromisedSeatCount > 0) {
    improvements.push({
      action: "Consider moving the primary seating row approximately 250 mm forward to improve bass consistency.",
      why: "Seat-to-seat bass variation is the primary remaining limitation.",
      benefit: "Improved response consistency across the primary listening area.",
    });
  }

  if (p20Primary && LEVEL_RANK[p20Primary] < 3) {
    improvements.push({
      action: "Consider additional rear subwoofers to improve seat-to-seat consistency.",
      why: "Seat consistency is below the reference threshold.",
      benefit: "More uniform bass response across all seating positions.",
    });
  }

  if (!meetsObjective && !primaryHasFail && dpi != null && dpi < 60) {
    improvements.push({
      action: "Consider increasing system capability if a higher RP22 performance level is required.",
      why: "The current system achieves a good but not reference-level performance.",
      benefit: "Higher RP22 performance levels across multiple parameters.",
    });
  }

  // ── Overall Assessment — fixed four-sentence structure ───────────────
  // 1. Design strength
  // 2. Primary achievement
  // 3. Remaining limitation
  // 4. Overall confidence
  const hasImprovements = improvements.length > 0;
  const overallAssessment = [
    buildStrengthSentence({ bassStrong, bassModerate, coverage }),
    buildAchievementSentence({ meetsObjective, primaryHasFail }),
    buildLimitationSentence({ primaryHasFail, hasImprovements, compromisedSeatCount }),
    buildConfidenceSentence({ meetsObjective, primaryHasFail }),
  ].join(" ");

  return {
    highlights,
    improvements,
    overallAssessment,
    designation,
    footer: ADI_FOOTER,
  };
}