export const BASS_NORMALIZED_PHYSICS_DEFAULTS = Object.freeze({
  surfaceAbsorption: Object.freeze({ front: 0.3, back: 0.3, left: 0.3, right: 0.3, ceiling: 0.3, floor: 0.3 }),
  qStrategy: "ab_corrected",
  enableRewCoreReflections: false,
  roomDamping: 20,
  axialQ: 4,
  modalSourceReferenceMode: "existing",
  modalGainScalar: 1,
  modalDistanceBlend: 0.55,
  modalStorageMode: "none",
  propagationPhaseScale: 0,
  disableReflectionPhaseJitter: false,
  disableReflectionCoherenceWeight: false,
  mute68HzAxialMode: false,
  debugDisableModalContribution: false,
  rewParityFieldMode: "full_field",
  overrideConstantAxialQ: false,
  overrideAbsorptionAxialQ: false,
  debugMode200Multiplier: 1,
  reflectionGainScale: 1,
  modalCoherenceMode: "coherent",
  highOrderAxialScale: 1,
  rewModalBandwidthScale: 0.55,
});