/**
 * SimulationDataExport.jsx
 * Diagnostic only — no production calculations modified.
 *
 * Exposes the exact arrays already generated by PhysicsSubstitutionShootout
 * for external analysis (Excel / Python). No interpolation, no smoothing,
 * no averaging — values are the raw freqsHz / spl arrays passed to the chart.
 *
 * Props:
 *   rows        — results.rows from PhysicsSubstitutionShootout (after run)
 *   rewEstimate — REW_ESTIMATE array (hardcoded reference, Variant F)
 */

import React, { useMemo } from 'react';

// ─── Band definitions ─────────────────────────────────────────────────────────
const BANDS = [
  { label: '20–50 Hz',   lo: 20,  hi: 50  },
  { label: '50–85 Hz',   lo: 50,  hi: 85  },
  { label: '85–160 Hz',  lo: 85,  hi: 160 },
  { label: '160–220 Hz', lo: 160, hi: 220 },
  { label: '85–220 Hz',  lo: 85,  hi: 220 },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
function interpREW(rewEstimate, hz) {
  const pts = [...rewEstimate].sort((a, b) => a.frequency - b.frequency);
  if (hz <= pts[0].frequency) return pts[0].spl;
  if (hz >= pts[pts.length - 1].frequency) return pts[pts.length - 1].spl;
  for (let i = 0; i < pts.length - 1; i++) {
    if (hz >= pts[i].frequency && hz <= pts[i + 1].frequency) {
      const t = (hz - pts[i].frequency) / (pts[i + 1].frequency - pts[i].frequency);
      return pts[i].spl + t * (pts[i + 1].spl - pts[i].spl);
    }
  }
  return null;
}

function fmt3(v) {
  return v !== null && v !== undefined && Number.isFinite(v) ? v.toFixed(3) : '';
}
function fmt2(v) {
  return v !== null && v !== undefined && Number.isFinite(v) ? v.toFixed(2) : '—';
}

// ─── Build unified frequency table ───────────────────────────────────────────
// Uses ONLY the exact freqsHz arrays from each variant row.
// All values are the raw SPL from the simulation arrays — no re-computation.
function buildUnifiedTable(rows, rewEstimate) {
  // Collect every frequency point that exists in any variant
  const freqSet = new Set();
  rows.forEach(r => {
    if (r.freqsHz) r.freqsHz.forEach(f => freqSet.add(f));
  });
  const sortedFreqs = Array.from(freqSet).sort((a, b) => a - b).filter(f => f >= 20 && f <= 220);

  // For each variant row, build a lookup map: freq → spl
  const variantMaps = {};
  rows.forEach(r => {
    if (!r.freqsHz || !r.spl) return;
    const m = new Map();
    r.freqsHz.forEach((f, i) => m.set(f, r.spl[i]));
    variantMaps[r.id] = m;
  });

  // Build the table rows — one per frequency point
  const tableRows = sortedFreqs.map(f => {
    const row = { hz: f };
    rows.forEach(r => {
      row[r.id] = variantMaps[r.id]?.get(f) ?? null;
    });
    row.F = interpREW(rewEstimate, f); // Variant F = REW estimate, interpolated to match grid
    return row;
  });

  return { tableRows, sortedFreqs };
}

// ─── CSV export ──────────────────────────────────────────────────────────────
function buildCSV(tableRows, variantIds, includeIds) {
  const ids = variantIds.filter(id => includeIds.includes(id) || id === 'F');
  const HEADER_MAP = {
    A: 'Production_SPL',
    B: 'ClassicalQ_SPL',
    C: 'Amplitude_SPL',
    D: 'Normalisation_SPL',
    E: 'Classical_SPL',
    F: 'REW_Estimate_SPL',
  };
  const cols = includeIds.concat(includeIds.includes('F') ? [] : ['F']).filter((v, i, a) => a.indexOf(v) === i);
  const header = ['Frequency_Hz', ...cols.map(id => HEADER_MAP[id] || id)].join(',');
  const dataLines = tableRows.map(row => {
    const vals = cols.map(id => {
      const v = row[id];
      return v !== null && v !== undefined && Number.isFinite(v) ? v.toFixed(4) : '';
    });
    return [row.hz.toFixed(4), ...vals].join(',');
  });
  return [header, ...dataLines].join('\n');
}

function downloadCSV(csv, filename) {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Banded MAE calculation (from raw arrays, no new simulation) ──────────────
function computeBandedStats(tableRows, idA, idB) {
  return BANDS.map(band => {
    const inBand = tableRows.filter(r => r.hz >= band.lo && r.hz <= band.hi);
    const pairs = inBand.filter(r =>
      r[idA] !== null && r[idA] !== undefined && Number.isFinite(r[idA]) &&
      r.F    !== null && r.F    !== undefined && Number.isFinite(r.F) &&
      r[idB] !== null && r[idB] !== undefined && Number.isFinite(r[idB])
    );
    if (pairs.length === 0) return { ...band, n: 0, maeA: null, maeB: null, diff: null, offsetA: null, offsetB: null, shapeA: null, shapeB: null };

    const maeA   = pairs.reduce((s, r) => s + Math.abs(r[idA] - r.F), 0) / pairs.length;
    const maeB   = pairs.reduce((s, r) => s + Math.abs(r[idB] - r.F), 0) / pairs.length;
    const offA   = pairs.reduce((s, r) => s + (r[idA] - r.F), 0) / pairs.length;
    const offB   = pairs.reduce((s, r) => s + (r[idB] - r.F), 0) / pairs.length;
    const shapeA = pairs.reduce((s, r) => s + Math.abs((r[idA] - offA) - r.F), 0) / pairs.length;
    const shapeB = pairs.reduce((s, r) => s + Math.abs((r[idB] - offB) - r.F), 0) / pairs.length;

    return {
      ...band,
      n: pairs.length,
      maeA,
      maeB,
      diff: maeB - maeA, // positive = B worse, negative = B better
      offsetA: offA,
      offsetB: offB,
      shapeA,
      shapeB,
    };
  });
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const cell  = { padding: '3px 8px', textAlign: 'right', fontSize: 10, fontFamily: 'monospace', borderBottom: '1px solid #e5e7eb', verticalAlign: 'middle' };
const cellL = { ...cell, textAlign: 'left' };
const th    = { ...cell, fontWeight: 700, color: '#1e3a8a', background: '#eff6ff', borderBottom: '2px solid #93c5fd' };
const thL   = { ...th, textAlign: 'left' };

function VerdictBadge({ diff }) {
  if (diff === null) return <span style={{ color: '#9ca3af', fontSize: 10 }}>—</span>;
  const absDiff = Math.abs(diff);
  if (absDiff < 0.3) {
    return <span style={{ background: '#f3f4f6', color: '#374151', padding: '1px 7px', borderRadius: 3, fontSize: 10, fontWeight: 700, fontFamily: 'monospace' }}>TIE ±{fmt2(absDiff)}</span>;
  }
  if (diff < 0) {
    return <span style={{ background: '#dcfce7', color: '#166534', padding: '1px 7px', borderRadius: 3, fontSize: 10, fontWeight: 700, fontFamily: 'monospace' }}>B better −{fmt2(absDiff)}</span>;
  }
  return <span style={{ background: '#fee2e2', color: '#991b1b', padding: '1px 7px', borderRadius: 3, fontSize: 10, fontWeight: 700, fontFamily: 'monospace' }}>A better +{fmt2(absDiff)}</span>;
}

// ─── Main component ───────────────────────────────────────────────────────────
export default function SimulationDataExport({ rows, rewEstimate }) {
  const variantRows = (rows || []).filter(r => !r.error && r.freqsHz?.length > 0 && r.spl?.length > 0);
  const variantIds  = variantRows.map(r => r.id); // e.g. ['A','B','C','D','E']

  const { tableRows, sortedFreqs } = useMemo(
    () => buildUnifiedTable(variantRows, rewEstimate || []),
    [rows, rewEstimate]
  );

  const bandedStats = useMemo(
    () => computeBandedStats(tableRows, 'A', 'B'),
    [tableRows]
  );

  // ─── Stats ────────────────────────────────────────────────────────────────
  const freqSpacing = sortedFreqs.length > 1
    ? ((sortedFreqs[sortedFreqs.length - 1] - sortedFreqs[0]) / (sortedFreqs.length - 1))
    : null;

  // ─── Export handlers ──────────────────────────────────────────────────────
  const handleExport = (ids, filename) => {
    const csv = buildCSV(tableRows, variantIds, ids);
    downloadCSV(csv, filename);
  };

  const btnStyle = (disabled) => ({
    height: 28,
    padding: '0 12px',
    borderRadius: 5,
    border: `1px solid ${disabled ? '#d1d5db' : '#1d4ed8'}`,
    background: disabled ? '#f3f4f6' : '#1d4ed8',
    color: disabled ? '#9ca3af' : '#fff',
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: 700,
    cursor: disabled ? 'not-allowed' : 'pointer',
    whiteSpace: 'nowrap',
  });

  const noData = tableRows.length === 0;

  return (
    <details style={{ border: '2px solid #7c3aed', borderRadius: 8, background: '#f5f3ff', padding: '8px 10px', marginTop: 10, marginBottom: 4 }}>
      <summary style={{ fontWeight: 700, color: '#7c3aed', fontSize: 11, fontFamily: 'monospace', cursor: 'pointer' }}>
        📤 Simulation Data Export — raw array inspection &amp; banded MAE (diagnostic only)
      </summary>

      <div style={{ marginTop: 8 }}>
        {/* Description */}
        <div style={{ fontSize: 10, fontFamily: 'monospace', color: '#5b21b6', lineHeight: 1.6, marginBottom: 10, background: '#ede9fe', borderRadius: 4, padding: '6px 8px' }}>
          Exports the exact arrays already produced by the shootout — the same values supplied to the chart.
          No interpolation, no smoothing, no new simulation. Requires the shootout to be run first.
          CSV is suitable for external analysis in Excel or Python.
        </div>

        {/* Statistics */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6, marginBottom: 10 }}>
          {[
            { label: 'Sample count', value: sortedFreqs.length > 0 ? sortedFreqs.length : '—' },
            { label: 'Min frequency', value: sortedFreqs.length > 0 ? `${sortedFreqs[0].toFixed(1)} Hz` : '—' },
            { label: 'Max frequency', value: sortedFreqs.length > 0 ? `${sortedFreqs[sortedFreqs.length - 1].toFixed(1)} Hz` : '—' },
            { label: 'Avg Δf (log-spaced)', value: freqSpacing ? `${freqSpacing.toFixed(3)} Hz` : '—' },
          ].map(({ label, value }) => (
            <div key={label} style={{ background: '#fff', border: '1px solid #ddd6fe', borderRadius: 5, padding: '5px 8px' }}>
              <div style={{ fontSize: 9, color: '#7c3aed', fontFamily: 'monospace', marginBottom: 2 }}>{label}</div>
              <div style={{ fontSize: 12, fontWeight: 700, color: '#1f2937', fontFamily: 'monospace' }}>{value}</div>
            </div>
          ))}
        </div>

        {/* Integrity checks */}
        <div style={{ fontSize: 10, fontFamily: 'monospace', background: noData ? '#fee2e2' : '#dcfce7', borderRadius: 5, padding: '5px 8px', marginBottom: 10, lineHeight: 1.7, color: noData ? '#991b1b' : '#166534' }}>
          {noData ? (
            '⚠ No data available — run the Physics Substitution Shootout first, then open this panel.'
          ) : (
            <>
              ✓ {sortedFreqs.length} frequency samples · {variantIds.length} simulation variants + REW estimate (F)<br />
              ✓ Values taken directly from freqsHz / spl arrays — not re-derived<br />
              ✓ Frequency range: {sortedFreqs[0]?.toFixed(1)} – {sortedFreqs[sortedFreqs.length - 1]?.toFixed(1)} Hz<br />
              ✓ REW (F) interpolated onto shared grid for MAE alignment only — export column labelled separately
            </>
          )}
        </div>

        {/* Export buttons */}
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 12 }}>
          <button disabled={noData || !variantIds.includes('A')} style={btnStyle(noData || !variantIds.includes('A'))}
            onClick={() => handleExport(['A', 'F'], 'B44_production_vs_REW.csv')}>
            Export Production A + REW (CSV)
          </button>
          <button disabled={noData || !variantIds.includes('B')} style={btnStyle(noData || !variantIds.includes('B'))}
            onClick={() => handleExport(['B', 'F'], 'ClassicalQ_vs_REW.csv')}>
            Export Classical Q B + REW (CSV)
          </button>
          <button disabled={noData} style={btnStyle(noData)}
            onClick={() => handleExport(['F'], 'REW_Estimate.csv')}>
            Export REW Estimate F (CSV)
          </button>
          <button disabled={noData} style={btnStyle(noData)}
            onClick={() => handleExport([...variantIds, 'F'], 'All_Variants_A-F.csv')}>
            Export All Variants A–F (CSV)
          </button>
        </div>

        {/* Banded MAE table — A vs B vs F, from raw arrays only */}
        {!noData && variantIds.includes('A') && variantIds.includes('B') && (
          <div style={{ marginBottom: 8 }}>
            <div style={{ fontWeight: 700, fontSize: 11, fontFamily: 'monospace', color: '#7c3aed', marginBottom: 6 }}>
              Banded MAE — A (Production) vs B (Classical Q) vs F (REW Estimate)
            </div>
            <div style={{ fontSize: 9, fontFamily: 'monospace', color: '#6b7280', marginBottom: 6 }}>
              Computed from the exported arrays only. Shape MAE = MAE after removing each band's mean level offset.
              B−A: negative = B closer to REW, positive = A closer to REW.
            </div>
            <div style={{ overflowX: 'auto' }}>
              <table style={{ borderCollapse: 'collapse', width: '100%', minWidth: 760 }}>
                <thead>
                  <tr>
                    <th style={{ ...thL, minWidth: 100 }}>Band</th>
                    <th style={th}>n pts</th>
                    <th style={{ ...th, color: '#213428' }}>MAE A (dB)</th>
                    <th style={{ ...th, color: '#0891b2' }}>MAE B (dB)</th>
                    <th style={th}>B−A (dB)</th>
                    <th style={th}>Offset A</th>
                    <th style={th}>Offset B</th>
                    <th style={{ ...th, color: '#213428' }}>Shape A</th>
                    <th style={{ ...th, color: '#0891b2' }}>Shape B</th>
                    <th style={{ ...thL, minWidth: 110 }}>Verdict</th>
                  </tr>
                </thead>
                <tbody>
                  {bandedStats.map((b, idx) => {
                    const isCombo = b.label === '85–220 Hz';
                    const bg = isCombo ? '#ede9fe' : idx % 2 === 0 ? '#fff' : '#faf9ff';
                    return (
                      <tr key={b.label} style={{ background: bg, fontWeight: isCombo ? 700 : 400 }}>
                        <td style={{ ...cellL, color: '#5b21b6', fontWeight: isCombo ? 700 : 500 }}>{b.label}</td>
                        <td style={cell}>{b.n ?? '—'}</td>
                        <td style={{ ...cell, color: '#213428', fontWeight: 600 }}>{fmt2(b.maeA)}</td>
                        <td style={{ ...cell, color: '#0891b2', fontWeight: 600 }}>{fmt2(b.maeB)}</td>
                        <td style={{ ...cell, color: b.diff !== null ? (b.diff < 0 ? '#0891b2' : '#dc2626') : '#9ca3af', fontWeight: 700 }}>
                          {b.diff !== null ? (b.diff >= 0 ? '+' : '') + fmt2(b.diff) : '—'}
                        </td>
                        <td style={{ ...cell, color: b.offsetA !== null && Math.abs(b.offsetA) > 2 ? '#b45309' : '#374151' }}>
                          {b.offsetA !== null ? (b.offsetA >= 0 ? '+' : '') + fmt2(b.offsetA) : '—'}
                        </td>
                        <td style={{ ...cell, color: b.offsetB !== null && Math.abs(b.offsetB) > 2 ? '#b45309' : '#374151' }}>
                          {b.offsetB !== null ? (b.offsetB >= 0 ? '+' : '') + fmt2(b.offsetB) : '—'}
                        </td>
                        <td style={{ ...cell, color: '#213428' }}>{fmt2(b.shapeA)}</td>
                        <td style={{ ...cell, color: '#0891b2' }}>{fmt2(b.shapeB)}</td>
                        <td style={cellL}><VerdictBadge diff={b.diff} /></td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>

            {/* Interpretation note */}
            <div style={{ fontSize: 9, fontFamily: 'monospace', color: '#6b7280', marginTop: 6, lineHeight: 1.6 }}>
              Offset = mean(variant − REW) per band. Positive = variant is louder than REW on average.
              Shape MAE = MAE after subtracting the mean offset — isolates curve shape from level shift.
              Values are computed from the same arrays written to the CSV — no additional simulation.
            </div>
          </div>
        )}

        {/* CSV format reminder */}
        <div style={{ fontSize: 9, fontFamily: 'monospace', color: '#6b7280', lineHeight: 1.6, marginTop: 4 }}>
          CSV columns: Frequency_Hz, Production_SPL, ClassicalQ_SPL, Amplitude_SPL, Normalisation_SPL, Classical_SPL, REW_Estimate_SPL
          (all-variants export). Empty cells = variant not run or frequency outside range.
          REW estimate (F) is screenshot-derived — not a calibrated measurement. Diagnostic use only.
        </div>
      </div>
    </details>
  );
}