/**
 * proposalWriterFixtures.mjs (test fixture)
 * ------------------------------------------
 * The drafts the Phase 2 contract tests validate: one compliant draft built from
 * whatever claims a pack allows, one Marquee-shaped draft written in the pack's
 * own words and figures, and small amendments that break exactly one rule each.
 *
 * Every claim ID used here is read out of the writer input, so a fixture can
 * never cite a claim a pack did not mint. Nothing here is generated by GPT: this
 * is the contract being tested, not the writer.
 */

import { WRITER_SECTIONS } from '../../base44/shared/proposalWriter/writerContractSchema.js';

/** The appendix carries no performance claim, and cites none. */
export const APPENDIX_NOTE = 'Sources: the Visual Report and the Technical Report saved for each option. '
  + 'Every figure in this proposal is quoted from those reports.';

/* ── The compliant draft ───────────────────────────────────────────────────── */

const claimOf = (input, area, kind) => (Array.isArray(input.allowed_claims) ? input.allowed_claims : [])
  .find((claim) => claim.area === area && claim.kind === kind) || null;

const claimsOfKind = (input, kind) => (Array.isArray(input.allowed_claims) ? input.allowed_claims : [])
  .filter((claim) => claim.kind === kind);

/** Which claims each section of the compliant draft is written from. */
const SECTION_CLAIMS = {
  decision_summary: (input) => [
    ...claimsOfKind(input, 'recommendation'),
    ...claimsOfKind(input, 'credibility').slice(0, 1),
  ],
  what_stays_same: (input) => ['room', 'screen_size', 'seating', 'system_layout']
    .map((area) => claimOf(input, area, 'shared_result')).filter(Boolean),
  what_changes: (input) => [
    claimOf(input, 'subwoofers', 'factual_change'),
    claimOf(input, 'p12', 'material_gain'),
  ].filter(Boolean),
  key_performance_highlights: (input) => [
    claimOf(input, 'p12', 'material_gain'),
    claimOf(input, 'p14', 'material_gain'),
    claimOf(input, 'p19', 'material_gain'),
  ].filter(Boolean),
  spatial_resolution: (input) => [
    claimOf(input, 'seating', 'shared_result'),
    claimOf(input, 'rp23_viewing', 'shared_result'),
    claimOf(input, 'p19', 'material_gain'),
  ].filter(Boolean),
  dynamic_range: (input) => [
    claimOf(input, 'p12', 'material_gain'),
    claimOf(input, 'p13', 'material_gain'),
    claimOf(input, 'p14', 'material_gain'),
  ].filter(Boolean),
  timbre_matching: (input) => [
    claimOf(input, 'p18', 'material_gain'),
    claimOf(input, 'p19', 'material_gain'),
    claimOf(input, 'speakers', 'shared_result'),
  ].filter(Boolean),
  overall_design: (input) => [
    ...claimsOfKind(input, 'credibility'),
    ...claimsOfKind(input, 'recommendation'),
  ],
  appendix_notes: () => [],
};

/** A compliant draft: each section states the pack's own claim wording. */
export function validDraft(input) {
  return {
    contract_version: input.contract_version,
    pack_fingerprint: input.evidence_pack.pack_fingerprint,
    sections: WRITER_SECTIONS.map((spec) => {
      const claims = (SECTION_CLAIMS[spec.section] || (() => []))(input).filter(Boolean);
      return {
        section: spec.section,
        text: claims.length > 0 ? claims.map((claim) => claim.statement).join(' ') : APPENDIX_NOTE,
        claim_ids: claims.map((claim) => claim.claim_id),
      };
    }),
  };
}

/* ── The Marquee draft ─────────────────────────────────────────────────────── */

const idsOf = (...claims) => claims.filter(Boolean).map((claim) => claim.claim_id);
const statementsOf = (...claims) => claims.filter(Boolean).map((claim) => claim.statement).join(' ');

/**
 * A compliant Marquee-style draft: the pack's own framing, its own figures, and
 * its own claim IDs. It is written the way the pack allows the Marquee
 * comparison to be described, and it states the recorded values verbatim.
 */
export function marqueeDraft(input) {
  const shared = (area) => claimOf(input, area, 'shared_result');
  const gain = (area, kind = 'material_gain') => claimOf(input, area, kind);
  const framing = input.evidence_pack?.decision_framing?.text || '';
  const bassNote = input.bass?.note || '';
  const p20 = claimOf(input, 'p20', 'modest_result') || claimOf(input, 'p20', 'shared_result');
  const credibility = claimsOfKind(input, 'credibility')[0] || null;
  const recommendation = claimsOfKind(input, 'recommendation')[0] || null;
  const subwooferChange = claimOf(input, 'subwoofers', 'factual_change');

  return {
    contract_version: input.contract_version,
    pack_fingerprint: input.evidence_pack.pack_fingerprint,
    sections: [
      {
        section: 'decision_summary',
        text: `${framing} ${statementsOf(recommendation)}`.trim(),
        claim_ids: idsOf(recommendation),
      },
      {
        section: 'what_stays_same',
        text: statementsOf(shared('room'), shared('screen_size'), shared('seating'), shared('system_layout')),
        claim_ids: idsOf(shared('room'), shared('screen_size'), shared('seating'), shared('system_layout')),
      },
      {
        section: 'what_changes',
        text: 'Level 4 is specified with SUB4-12 x 4 rather than SUB3-12 x 2. '
          + 'Front-stage dynamic range moves from 100 dBC to 116 dBC.',
        claim_ids: idsOf(subwooferChange, gain('p12')),
      },
      {
        section: 'key_performance_highlights',
        text: 'P12 records 116 dBC at L4, P13 records 112 dBC at L4 and P14 records 120 dB at L4.',
        claim_ids: idsOf(gain('p12'), gain('p13'), gain('p14')),
      },
      {
        section: 'spatial_resolution',
        text: 'P19 holds +/-3 dB in the Level 1 design and +/-2 dB in the Level 4 design, '
          + 'measured across the same seating rows.',
        claim_ids: idsOf(gain('p19')),
      },
      {
        section: 'dynamic_range',
        text: 'P12 rises to 116 dBC and P14 to 120 dB, so demanding passages keep their composure without strain.',
        claim_ids: idsOf(gain('p12'), gain('p14')),
      },
      {
        section: 'timbre_matching',
        text: 'P18 extends to 20 Hz in the Level 4 design and P19 holds coverage at +/-2 dB.',
        claim_ids: idsOf(gain('p18'), gain('p19')),
      },
      {
        section: 'overall_design',
        text: `${bassNote} ${statementsOf(gain('p14'), credibility)}`.trim(),
        claim_ids: idsOf(p20, gain('p14'), credibility),
      },
      { section: 'appendix_notes', text: APPENDIX_NOTE, claim_ids: [] },
    ],
  };
}

/* ── Amendments that break exactly one rule each ───────────────────────────── */

/**
 * The compliant draft with one section amended: a sentence appended, and any
 * extra claim IDs added to that section's grounding.
 */
export function amend(input, { section, sentence = null, claim_ids = [], replace_text = null } = {}) {
  const draft = validDraft(input);
  const target = draft.sections.find((entry) => entry.section === section);
  if (!target) throw new Error(`The fixture draft has no ${section} section.`);
  if (replace_text !== null) target.text = replace_text;
  if (sentence) target.text = `${target.text} ${sentence}`;
  for (const id of claim_ids) if (!target.claim_ids.includes(id)) target.claim_ids.push(id);
  return draft;
}

/** The compliant draft with one section carrying no claim IDs at all. */
export function withoutClaimIds(input, section) {
  const draft = validDraft(input);
  const target = draft.sections.find((entry) => entry.section === section);
  target.claim_ids = [];
  return draft;
}

/** The compliant draft with exactly this section's text replaced. */
export function withSectionText(input, section, text) {
  return amend(input, { section, replace_text: text });
}

/** The compliant draft with an extra top-level field. */
export function withExtraTopLevelField(input) {
  return { ...validDraft(input), notes: 'internal working notes' };
}

/** A draft as the raw text a writer returns. */
export function asOutputText(draft) {
  return JSON.stringify(draft);
}