/** Proposal-only narrative contract. No calculations, storage or report rendering. */
const PARAMETER_EXPERIENCE = Object.freeze({
  P2: 'Discrete channel capability: physical positions for sound around and above the seats. Explain placement and the potential for smoother movement; channel count alone does not prove good spacing or coverage.',
  P5: 'Horizontal speaker spacing: adjacent gaps govern how naturally effects travel around the listener rather than jumping between speakers. Use the assessed spacing and seat scope.',
  P7: 'Front wide position: deviation governs the handover between the screen stage and side walls, helping front-to-side movement feel continuous where positioning supports it.',
  P9: 'Overhead spacing: vertical angles govern front-to-back motion above the audience, not simply sound coming from above.',
  P12: 'Screen Dynamic Range: LCR output capability supports headroom, screen authority, cleaner dialogue during demanding scenes, larger music and stronger effects. It is predicted capability, not a measured distortion or dialogue-intelligibility guarantee.',
  P13: 'Non-screen Dynamic Range: surround and overhead capability lets the immersive field keep pace with the front stage in busy scenes instead of losing presence.',
  P14: 'LFE / subwoofer Dynamic Range: bass output capability supports weight, physical impact and composure for explosions, score and tension at the assessed listening level. It does not establish deeper extension, smoother response or evenness across seats.',
  P16: 'Screen timbre: assessed response consistency supports natural, stable voices across the screen and a stronger connection between picture and sound.',
  P17: 'Surround / overhead timbre: assessed response consistency helps an effect keep its character as it travels around and above listeners, creating a coherent sound field. Product family alone is not proof of this result.',
  P18: 'Bass extension: the supplied low-frequency limit describes how deeply the room can reproduce soundtrack content rather than stopping short. Do not imply reproduction below the assessed limit.',
  P19: 'Bass response at RSP: response versus target describes balance and control at the reference listening position, not every seat. Avoid promising the absence of boom or thinness if deviations remain.',
  P20: 'Bass consistency: supplied seat-to-seat variation describes how similarly seats experience bass. Smaller comparable variation supports a relative improvement only where evidence rules permit a positive claim; otherwise disclose the values neutrally. Never promise equal bass or infer improvement from more subwoofers.',
  RP23: 'Viewing geometry: horizontal viewing angle and each row level explain image involvement and scale. Keep row scope; a stronger result is not proof that a larger angle is always preferable or that every seat has the same view.',
});

const SECTION_STORY = Object.freeze({
  system_design_summary: 'Orient the reader with the real room and system, then name the principal supported performance advantage. In a comparison, keep shared facts brief and explain who each option suits without choosing for the client. A short evidence-backed headline is allowed; do not duplicate the table.',
  spatial_resolution: 'Explain shared P2 capability first where relevant, then choose the important assessed P5/P7/P9 differences. Say what listeners should hear moving across the screen, around the room and overhead. If geometry is shared, the higher specification does not earn better panning merely from different speakers.',
  dynamic_range: 'Give P12 and P14 their own short evidence-to-experience paragraphs when reliable results exist for the selected versions. Include P13 where useful. Name both values and achieved levels, connect the equipment change to the supported output difference, then to dialogue, music, screen authority, bass impact and composure. Explain that the point is staying clean when the soundtrack becomes demanding, not simply playing louder.',
  timbre_matching: 'Translate reliable P16/P17 into stable voices and effects that retain their character. Separately explain reliable P18/P19/P20, retaining their individual scopes. Do not assume more subwoofers improve extension or consistency.',
  overall_design: 'Finish with a clear buying decision, not a recap of specifications: what the sensible option keeps and what the higher specification adds for clients seeking cinema-scale impact and more effortless playback. Be compelling where evidence supports it and candid about trade-offs. Fun and excitement may describe the expected listening experience, never a guaranteed outcome.',
  key_performance_highlights: 'Write only the short introduction or the requested experience cells. The app owns the real table, every row, value, level and column. Do not generate a replacement table or repeat its measurements in the introduction.',
});

export function buildProposalSalesVoice(sectionType, proposalType = 'system_summary') {
  const comparison = proposalType === 'comparison';
  return [
    '=== PROPOSAL-ONLY SALES VOICE: FINAL NARRATIVE DIRECTION ===',
    'This direction governs proposal prose only. Keep all factual, evidence reliability, assumed-parameter exclusion, design-stage and table rules above. Where older prose guidance conflicts with this voice, follow this direction: measured enthusiasm and a compelling explanation are welcome; empty praise is not.',
    'Write like a senior high-end cinema designer and salesperson explaining why the engineering is worth considering. Calm confidence, warmth, passion and practical clarity. Premium, not shouty. Sell the experience created by good engineering, not the equipment list. No invented personal experience or claims of having heard this room.',
    'Use short direct sentences, active voice and varied openings. Prefer cleaner dialogue, more scale, more presence, smoother panning, stronger front stage, greater headroom, physical impact, a coherent immersive field and more effortless playback, but only for the parameter that supports each benefit.',
    'Never open with "The screen does", "The speakers do", "The subwoofers provide" or "The system is designed to". Prefer "The main upgrade is...", "This matters because...", "That headroom gives the front stage..." or "For the listener, that means...". Do not mechanically reuse these openings.',
    'For every important result: engineering fact -> RP22/RP23 parameter result -> what it enables -> what listeners should experience during a film. Name the parameter in plain language with its code once per discussed parameter, not once per section. Quote the exact supplied value, unit and achieved level. A saved version name containing a level is an option label, not that parameter\'s achieved level.',
    'Compare both option values together when needed; the old one-or-two-values-per-paragraph limit must not prevent an honest before/after comparison. Keep paragraphs short and avoid a parameter-by-parameter lecture. Introductions to calculated tables remain value-free.',
    'Preserve predicted versus measured status. Say "predicted capability", "the assessment shows" or "should" where appropriate, not "confirms measured playback" for a simulation. Do not promise distortion-free playback, perfect coverage, equal bass, exact perceived loudness gains or guaranteed dialogue clarity.',
    'Do not use "elevates the experience", "immersive like never before", "unparalleled", "ultimate", "world-class", "cinematic journey", "a testament to" or "revolutionary" in client copy. Avoid "incredible"; use "crystal-clear" only with direct supporting evidence and preferably explain the actual clarity mechanism instead.',
    'Every claim must be traceable to the supplied frozen evidence for that exact option, parameter and seat/row scope. Missing, stale, unreliable and assumed results cannot support a claim. A model, price, version name or subwoofer count is not proof of a performance improvement.',
    comparison ? 'COMPARISON DECISION: use all selected versions and the calculated comparison evidence, never the primary snapshot or legacy project specification as an authority for every option. Exact saved version names are mandatory. Explain what is shared, the principal equipment change, the actual parameter values and levels, then the listening consequence. The stronger option may be described decisively where supported, never automatically as best.' : 'SINGLE PROPOSAL: explain this version\'s actual design and supported experience. Do not invent a comparison or upgrade.',
    comparison ? 'When all options share 9.1.6 / 15 discrete main channels and P2 Level 4, make it a shared strength. The upgrade is not more channels; it is what those channels can deliver under demanding soundtracks. Do not turn a shared layout into a higher-option spatial advantage.' : '',
    comparison ? 'Explicitly disclose every real trade-off: if P17 is lower in the higher-output option, say which option retains the stronger assessed surround/overhead timbre and which gives it up for output capability. Do not present a uniform upgrade. If P20 is absent, do not claim maximum seat-to-seat bass consistency, even if a legacy strategy description says it.' : '',
    comparison ? 'Respect the lower specification. It can be credible, capable, sensible, practical or cost-conscious, where supported. Never call it weak, inadequate or a mistake. Explain what it retains before what the higher option adds. State real limitations without pretending a Level 1/2 parameter is top-level performance.' : '',
    comparison ? 'Use conditional writing patterns, never hard-coded example facts: "[higher option]\'s [LCR model] screen stage is the main upgrade. Parameter 12 rises from [first value and level] to [second value and level]. That headroom supports [specific front-stage benefit]." For bass use P14 for impact, P18 for depth, P19 for RSP balance and P20 for seat consistency separately. Omit any missing part.' : '',
    '=== PARAMETER TO EXPERIENCE GUIDE (use only supplied results) ===',
    ...Object.entries(PARAMETER_EXPERIENCE).map(([key, text]) => `${key}: ${text}`),
    SECTION_STORY[sectionType] || 'Explain the relevant engineering choice and its listening consequence without adding sections or repeating the evidence table.',
    'FINAL SILENT CHECK: Is the principal advantage clear and compelling? Does each important result have an experiential meaning? Are all numbers and levels exact and attached to the right option? Are shared strengths credited to both? Is the lower option respected? Are bass depth, output, RSP balance and seat consistency kept separate? Remove hype, unsupported claims, generic filler and any invented facts. Return only the requested content.',
  ].filter(Boolean).join('\n\n');
}

export default buildProposalSalesVoice;