
export function serializeProject(input) {
  const {
    name,
    roomDims = { widthM: 4.5, lengthM: 6.0, heightM: 2.4 },
    dimensions = {},
    screen = {},
    screenHeight = 0.5,
    seatingPositions = [],
    placedSpeakers = [],
    roomElements = [],
    subwoofers = [],
    dolbyLayout = "5.1",
    overlays = {},
    frozenTabs = {},
    sevenBedLayoutType = 'rears',
    speakerSelections = {},
    enableFrontWides = false,
    rowSpacingM = 1.8,
    seatsPerRowByRow = [], // NEW
    overheadGlobalModel = null,
    overheadFrontOverride = null,
    overheadMidOverride = null,
    overheadRearOverride = null,
    useFrontGlobal = true,
    useMidGlobal = true,
    useRearGlobal = true,
    splConfig = { globalPowerW: 100, globalEqHeadroomDb: 0, perRole: {} },
    screenFrontPlaneM = 0,
  } = input;

  return {
    name: name || "Untitled Room",
    room_width: Number(roomDims?.widthM || dimensions?.width) || 0,
    room_length: Number(roomDims?.lengthM || dimensions?.length) || 0,
    room_height: Number(roomDims?.heightM || dimensions?.height) || 0,
    roomDims: JSON.stringify(roomDims),
    screen_size: Number(screen?.visibleWidthInches) || 0,
    aspect_ratio: screen?.aspectRatio || "16:9",
    manual_dimensions: !!screen?.manualMode,
    manual_width_m: Number(screen?.manualWidthM) || 0,
    manual_height_m: Number(screen?.manualHeightM) || 0,
    screen_height_from_floor: Number(screen?.heightFromFloorM ?? 0),
    dolby_config: dolbyLayout || "5.1",
    seating_positions: JSON.stringify(Array.isArray(seatingPositions) ? seatingPositions : []),
    selected_speakers: JSON.stringify(Array.isArray(placedSpeakers) ? placedSpeakers : []),
    room_elements: JSON.stringify(Array.isArray(roomElements) ? roomElements : []),
    subwoofers: JSON.stringify(Array.isArray(subwoofers) ? subwoofers : []),
    overlays: JSON.stringify(overlays || {}),
    screen_mount_mode: "floating",
    float_depth_m: Number(screen?.floatDepthM) || 0,
    show_screen_plane: !!screen?.showScreenPlane,
    show_cavity: !!screen?.showCavity,
    speaker_clearance_m: Number(screen?.speakerClearanceM ?? 0.02) || 0.02,
    frozen_tabs: frozenTabs,
    seven_bed_layout_type: sevenBedLayoutType,
    speaker_selections: JSON.stringify(
      typeof speakerSelections === 'object' && speakerSelections !== null
        ? speakerSelections
        : {}
    ),
    enable_front_wides: !!enableFrontWides,
    row_spacing_m: Number(rowSpacingM) || 1.8,
    seats_per_row_by_row: JSON.stringify(Array.isArray(seatsPerRowByRow) ? seatsPerRowByRow : []), // NEW
    overhead_global_model: overheadGlobalModel,
    overhead_front_override: overheadFrontOverride,
    overhead_mid_override: overheadMidOverride,
    overhead_rear_override: overheadRearOverride,
    use_front_global: useFrontGlobal,
    use_mid_global: useMidGlobal,
    use_rear_global: useRearGlobal,
    spl_config: JSON.stringify(splConfig),
    screen_front_plane_m: Number(screenFrontPlaneM) || 0,
  };
}
